Update the documentation to cross compile nexad on win64 system
The depends system expect the compiler to use the POSIX threading
model. this is not the default gcc configuration while cross compiling
for windows.

Without this commit libboost compilation would fail with this error
message:

```
Building boost...
/home/user/src/NEXA/nexa/depends/work/build/x86_64-w64-mingw32/boost/1.86.0-b49bed941db/tools/build/src/tools/common.jam:1104:
in common.find-compiler from module common
error: toolset gcc initialization:
error: provided command '"x86_64-w64-mingw32-g++"' not found
error: initialized from
/home/user/src/NEXA/nexa/depends/work/build/x86_64-w64-mingw32/boost/1.86.0-b49bed941db/user-config.jam:1
/home/user/src/NEXA/nexa/depends/work/build/x86_64-w64-mingw32/boost/1.86.0-b49bed941db/tools/build/src/tools/gcc.jam:165:
in gcc.init from module gcc
/home/user/src/NEXA/nexa/depends/work/build/x86_64-w64-mingw32/boost/1.86.0-b49bed941db/tools/build/src/build/toolset.jam:42:
in toolset.using from module toolset
/home/user/src/NEXA/nexa/depends/work/build/x86_64-w64-mingw32/boost/1.86.0-b49bed941db/tools/build/src/build/project.jam:1291:
in using from module project-rules
/home/user/src/NEXA/nexa/depends/work/build/x86_64-w64-mingw32/boost/1.86.0-b49bed941db/user-config.jam:1:
in modules.load from module user-config
/home/user/src/NEXA/nexa/depends/work/build/x86_64-w64-mingw32/boost/1.86.0-b49bed941db/tools/build/src/build-system.jam:255:
in load-config from module build-system
/home/user/src/NEXA/nexa/depends/work/build/x86_64-w64-mingw32/boost/1.86.0-b49bed941db/tools/build/src/build-system.jam:449:
in load-configuration-files from module build-system
/home/user/src/NEXA/nexa/depends/work/build/x86_64-w64-mingw32/boost/1.86.0-b49bed941db/tools/build/src/build-system.jam:607:
in module scope from module build-system
make: *** [funcs.mk:253:
/home/user/src/NEXA/nexa/depends/work/build/x86_64-w64-mingw32/boost/1.86.0-b49bed941db/./.stamp_built]
Error 1
```

Also change the way `configure` need to be run in order to avoid
compilation problems under some specific conditions.